### ISSUE TITLE
create searchable pdf extend of stdout

### ISSUE THREAD

**Issue by zkukulj** [thiagoalessio/tesseract-ocr-for-php#74] opened 2017-04-07 17:31 UTC
Had to create searchable pdf from tif, since new tessaract provides making one I have added (to appropriate places in TessaractOCR class:
private $outtype;
public function outtype($outtype)    {
$this->outtype = $outtype;
return $this;
} 
Small change in buildCommand, removed stdout by default
protected function buildCommand()    {
        return $this->executable.' '.escapeshellarg($this->image).' '
            .$this->buildOuttype()
	    .$this->buildTessdataDirParam()
            .$this->buildUserWordsParam()
            .$this->buildUserPatternsParam()
            .$this->buildLanguagesParam()
            .$this->buildPsmParam()
            .$this->buildConfigurationsParam();
}

private function buildOuttype()    {
return $this->outtype ? "$this->outtype" : 'stdout';
}

usage similar to 
$tess=(new TesseractOCR('demo.tif'))->lang('eng')->outtype('yournewfilename pdf')->config('tessedit_create_pdf','1','tessedit_pageseg_mode','1')->run();

Generates great searchable pdfs. (Many thanks Thiago for this great class!)

**Comment by thiagoalessio** [comment] 2017-05-14 11:02
Hey, this actually looks interesting ! I'll close this issue (since it is a new feature, not a bug on the library) and I'd ask you to create a pull request instead. will be a nice addition to the lib ;D

**Closed by thiagoalessio** 2017-05-14 11:02 UTC
