### ISSUE TITLE
TesseractOCR returning empty response?

### ISSUE THREAD

**Issue by Maxenus** [thiagoalessio/tesseract-ocr-for-php#81] opened 2017-06-15 08:41 UTC
Hi,

I tried installing Tesseract-OCR in my computer and load TesseractOCR.php in my php file. However, when I use the following the response is empty.

```
$tesseractOcr = new TesseractOCR(imageFilePath);
$tesseractOcrResult = $tesseractOcr->run();
print_r($tesseractOcrResult);
```

Additionally, when I run the command
```
tesseract.exe imageFilePath test
```
in CMD it returns the error
```
Tesseract Open Source OCR Engine v3.05.01 with Leptonica
Warning. Invalid resolution 0 dpi. Using 70 instead.
```

Anything that I did wrong?

**Comment by MarwaZeidan35** [comment] 2017-06-15 11:51
I have the same issue.

**Comment by daniyaleight** [comment] 2017-06-17 14:53
I have the same problem too.

this is my code but in the output nothing printed.
`<?php
echo "<h2><center>";
require-once __DIR__ . '/vendor/autoload.php';
$path="german.png";
$resu1t= new TesseractOCR($path);
$text=$resu1t->lang('deu')->run();
echo Stext;
echo "</center></h2>";`

**Comment by TariGit** [comment] 2017-06-21 15:50
I think that the problem is in the image that you try to scan, try to prove with a picture it look better

**Comment by daniyaleight** [comment] 2017-06-22 04:24
german.png is the same picture which has been put in the documentation.!!

**Comment by thiagoalessio** [comment] 2017-07-03 18:40
ok, apparently you are having problems with Tesseract itself, not with this PHP wrapper. closing this issue.

**Closed by thiagoalessio** 2017-07-03 18:40 UTC

**Comment by daniyaleight** [comment] 2017-07-11 07:38
So what should I do to solve this problem?

**Comment by deguilardi** [comment] 2018-02-16 14:57
Same here, no matter what image I try, it always returns null responses.

PHP 5.4
OSX 10.13

![screen shot 2018-02-15 at 9 53 32 am](https://user-images.githubusercontent.com/16661903/36313538-ce9e90d8-12ff-11e8-9736-a02a00e8ae29.png)

**Comment by thiagoalessio** [comment] 2018-02-16 15:04
The library requires PHP 5.6 or greater to work: https://github.com/thiagoalessio/tesseract-ocr-for-php/blob/master/composer.json#20

**Comment by deguilardi** [comment] 2018-02-16 15:06
Alright, I followed the breadcrumbs and ran the following command on the terminal directly and it worked (on the terminal).
`"tesseract" "test2.png" stdout`

If you'd take @Maxenus seriously you'd have make it work.

**Comment by deguilardi** [comment] 2018-02-16 15:07
My bad, the server I was logged on has php 5.4 the one I'm trying this lib is:

PHP 5.6.31 (cli) (built: Aug  7 2017 20:28:40) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
